title: 刘荣清's 博客
sass:
  style: compressed
plugins:
  - jemoji
permalink: /:title
timezone: Asia/Shanghai
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "page"