title: 刘荣清's 博客
url: https://www.liurongqing.com
host: 0.0.0.0
sass:
  style: compressed
plugins:
  - jemoji
  - jekyll-paginate
paginate: 10
permalink: /:title
timezone: Asia/Shanghai
excerpt_separator: <!--more-->
defaults:
  -
    scope:
      path: "_posts"
    values:
      layout: "page"